//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int NOTIF_ID { get; set; }
        public string NOTIF_TYPE { get; set; }
        public int RECEIVER_ID { get; set; }
        public int SENDER_ID { get; set; }
        public int CREATED_DATE { get; set; }
        public int LIKES_ID { get; set; }
        public int COMMENT_ID { get; set; }
        public int POST_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public string SEEN { get; set; }
    }
}
